
import java.util.HashSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class CadPes extends javax.swing.JFrame {
    private Pessoa p1 = new Pessoa();
    private GerPes gp = new GerPes();
    /**
     * Creates new form CadPes
     */
    public CadPes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtCpf = new javax.swing.JLabel();
        cxCpf = new javax.swing.JTextField();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btInPes = new javax.swing.JButton();
        btConsPesCpf = new javax.swing.JButton();
        btAltPesCpf = new javax.swing.JButton();
        btExcPesCpf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rafael\n");
        setBackground(new java.awt.Color(255, 51, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        rtCpf.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 18)); // NOI18N
        rtCpf.setForeground(new java.awt.Color(255, 0, 0));
        rtCpf.setText("CPF:");

        cxCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCpfActionPerformed(evt);
            }
        });

        rtNome.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        rtNome.setForeground(new java.awt.Color(255, 51, 51));
        rtNome.setText("Nome:");
        rtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.NW_RESIZE_CURSOR));

        cxNome.setForeground(new java.awt.Color(102, 255, 0));

        btSair.setBackground(new java.awt.Color(0, 0, 255));
        btSair.setFont(new java.awt.Font("Source Code Pro", 3, 12)); // NOI18N
        btSair.setForeground(new java.awt.Color(255, 255, 0));
        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(102, 153, 0));
        btLimpar.setFont(new java.awt.Font("Source Code Pro", 3, 12)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(255, 255, 0));
        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btInPes.setText("Inserir");
        btInPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInPesActionPerformed(evt);
            }
        });

        btConsPesCpf.setText("Consultar por CPF");
        btConsPesCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsPesCpfActionPerformed(evt);
            }
        });

        btAltPesCpf.setText("Alterar CPF");

        btExcPesCpf.setText("Excluir CPF");
        btExcPesCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcPesCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInPes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcPesCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAltPesCpf)
                        .addGap(18, 18, 18)
                        .addComponent(btConsPesCpf))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpar)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNome)
                    .addComponent(rtCpf))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxNome)
                    .addComponent(cxCpf))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInPes)
                    .addComponent(btExcPesCpf)
                    .addComponent(btAltPesCpf)
                    .addComponent(btConsPesCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btLimpar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCpfActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btInPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInPesActionPerformed
        insPes();
    }//GEN-LAST:event_btInPesActionPerformed

    private void btExcPesCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcPesCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcPesCpfActionPerformed

    private void btConsPesCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsPesCpfActionPerformed
        consCpf();
    }//GEN-LAST:event_btConsPesCpfActionPerformed

    public void consCpf(){
        p1 = new Pessoa();
        try{
            p1.setCpf(Integer.parseInt(cxCpf.getText()));
            
            p1 = gp.consPesCpf(p1);
            
            if(p1 != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Consulta:\nNOME: "+p1.getNome()+"\nCPF:     "+p1.getCpf(),
                        "Consulta de Pessoa",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "CPF nao existe!",
                        "Consulta de Pessoa",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO! O CPF deve ser um inteiro",
                    "Insercao de pessoa",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    } 
    
    public void insPes(){
        p1 = new Pessoa();
        
        try{
            p1.setCpf(Integer.parseInt(cxCpf.getText()));
            p1.setNome(cxNome.getText());

            p1 = gp.insPes(p1);

            if(p1 != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Cadastro realizado!",
                        "Insercao de Pessoa",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "CPF Duplicado, já existe esse CPF",
                        "Insercao de pessoa",
                        JOptionPane.ERROR_MESSAGE
                );
            }
            cxCpf.setText("");
            cxCpf.requestFocus();
        }//fim try
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO! O CPF deve ser um inteiro",
                    "Insercao de pessoa",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    public void limpar(){
        cxCpf.setText("");
        cxNome.setText("");
        cxCpf.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltPesCpf;
    private javax.swing.JButton btConsPesCpf;
    private javax.swing.JButton btExcPesCpf;
    private javax.swing.JButton btInPes;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxNome;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtNome;
    // End of variables declaration//GEN-END:variables
}
